
name: Simple Github Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "Building..."
        
        
    - name: Test
      run: |
        echo "Running tests..."
        # Add your test commands here
        
    - name: Deploy
      run: |
        echo "Deploying..."
        # Add your deployment commands here
